//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EPncUI.rc
//
#define IDC_LISTBOX_NCFILE              101
#define IDC_LISTBOX_P1_FILENGR          102
#define IDC_LISTBOX_P1_SDMEM_NCFILE     103
#define IDC_LISTBOX_P2_SDMEM_NCFILE     104
#define IDC_LISTBOX_P2_USBMEM_NCFILE    105
#define IDC_SETUP_IOLISTBOX_INPUT       106
#define IDC_LISTBOX_USB_NCFILE_LIST     107
#define IDC_LISTBOX_RUN_TIME            108
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_FILE_COPY            134
#define IDD_DIALOG_ERROR                135
#define IDD_DIALOG_SETUP                136
#define IDD_DIALOG_SETUP_TEACHING       137
#define IDD_DIALOG_SETUP_MENU           138
#define IDD_DIALOG_SETUP_TOOL           139
#define IDD_DIALOG_SETUP_TOOL_RESET     140
#define IDD_DIALOG_NUMERIC_INPUT        141
#define IDD_DIALOG_REGISTER_RELATED_TOOL 142
#define IDD_DIALOG_SEL_JOG_STEP         143
#define IDD_DIALOG_SETUP_TEACHING_COORD_OFFSET 144
#define IDD_DIALOG_SETUP_TEACHING_TEACHING_POINT 145
#define IDD_DIALOG_SETUP_TEACHING_OFFSET 146
#define IDD_DIALOG_MSG                  148
#define IDD_DIALOG_SETUP_OPTION         153
#define IDD_DIALOG_PASSWORD             154
#define IDD_DIALOG_SETUP_IO             155
#define IDD_DIALOG_SETUP_TERMINAL       156
#define IDD_DIALOG_SETUP_LOG            157
#define IDD_DIALOG_CALCULATOR           158
#define IDD_DIALOG_SETUP_SYSTEM         159
#define IDD_DIALOG_SETUP_SYSTEM_SOFTLIMIT 160
#define IDD_DIALOG_SETUP_SYSTEM_TOOL    161
#define IDD_DIALOG_RESTART              163
#define IDD_EPNCUI_DIALOG2              165
#define IDB_BITMAP_ERROR                166
#define IDB_BITMAP_INFO                 167
#define IDB_BITMAP_QUEST                168
#define IDB_BITMAP_WARM                 169
#define IDD_DIALOG_SETUP_TEACHING_AUTOCAL_COORD_OFFSET 170
#define IDD_DIALOG_SETUP_TEACHING_AUTO_TEACHING 171
#define IDD_DIALOG_MAXXLINK_SERVICE     174
#define IDB_BITMAP_SERVICE              175
#define IDD_DIALOGIDD_DIALOG_SETUP_SYSTEM_RUN_TIME 176
#define IDD_DIALOG_SETUP_SYSTEM_CHAGE_IP 178
#define IDD_DIALOG_SETUP_SYSTEM_ATCTEST 179
#define IDD_DIALOG_RESET_ORIGIN         180
#define IDD_DIALOG_SETUP_SYSTEM_FILTER_MANAGEMENT 181
#define IDD_DIALOG1                     182
#define IDD_DIALOG_SPLASH               182
#define IDD_DIALOG_CONNECT_ERROR        183
#define IDD_DIALOG_SETUP_TOOL_SET       184
#define IDD_DIALOG_SETUP_MAINTENANCE    185
#define IDD_DIALOG_NUMERIC_INPUT_TIME   186
#define IDD_DIALOG_SETUP_AUTOTEACH      188
#define IDB_BITMAP_AC_EQUIPMENT         188
#define IDD_DIALOG_SETUP_AUTOTEACH1     189
#define IDD_DIALOG_SETUP_AUTOTEACH_STEP1 189
#define IDB_BITMAP_AC_SWITCH            189
#define IDD_DIALOG_SETUP_TOOL1          190
#define IDD_DIALOG_SETUP_AUTOTEACH_STEP7 190
#define IDB_BITMAP_AC_TOOLS1            190
#define IDD_DIALOG_SETUP_TEACHING_AUTO_TEACHING1 191
#define IDD_DIALOG_SETUP_AUTOTEACH_STEP5 191
#define IDB_BITMAP_AC_TOOLS2            191
#define IDD_DIALOG_SETUP_AUTOTEACH_STEP6 192
#define IDB_BITMAP_AC_TOOLS3            192
#define IDD_DIALOG_SETUP_AUTOTEACH_STEP2 193
#define IDD_DIALOG_SETUP_AUTOTEACH_STEP3 194
#define IDB_BITMAP_AT_MOUNTED           194
#define IDD_DIALOG_SETUP_AUTOTEACH_STEP4 195
#define IDB_BITMAP_AT_CABLE_CLAMP       195
#define IDB_BITMAP_AT_CONDUCTION_OFF    196
#define IDD_DIALOG_SETUP_AUTOCAL_STEP1  196
#define IDD_DIALOG_SETUP_AUTOCAL_STEP2  197
#define IDB_BITMAP_AT_CONDUCTION_ON     198
#define IDD_DIALOG_SETUP_AUTOCAL_STEP3  198
#define IDD_DIALOG_SETUP_AUTOCAL_STEP4  199
#define IDB_BITMAP_AC_READY             199
#define IDD_DIALOG_SETUP_AUTOCAL_STEP5  200
#define IDD_DIALOG_SETUP_AUTOCAL_STEP6  201
#define IDD_DIALOG_SETUP_AUTOTEACH2     202
#define IDD_DIALOG_SETUP_AUTOCAL        202
#define IDB_BITMAP_AC_MOUNTED           202
#define IDB_BITMAP_AC_CONDUCTION_OFF    203
#define IDB_BITMAP_AC_CONDUCTION_ON     204
#define IDB_BITMAP_AT_READY             205
#define IDB_BITMAP_AC_CYLINDER          209
#define IDB_BITMAP1                     210
#define IDB_BITMAP_AT_ATC               210
#define IDB_BITMAP_AT_ATC_CLEAN         211
#define IDB_BITMAP_AT_ATC_cleaning      211
#define IDB_BITMAP2                     212
#define IDB_BITMAP_AT_EQUIPMENT         212
#define IDC_BUTTON_OPEN                 1005
#define IDC_BUTTON_RUN                  1006
#define IDC_BUTTON_STOP                 1013
#define IDC_BUTTON_CLOSE                1015
#define IDC_BUTTON_NEXT                 1016
#define IDC_BUTTON_PREVIOUS             1017
#define IDC_PROGRESS1                   1035
#define IDC_PROGRESS2                   1036
#define IDC_BUTTON_CANCEL               1037
#define IDC_STATIC_TEXT                 1038
#define IDC_BUTTON_OK                   1043
#define IDC_CHECK_MELODY_OFF            1044
#define IDC_BUTTON_NO                   1044
#define IDC_STATIC_TYPE                 1045
#define IDC_STATIC_MESSAGE              1046
#define IDC_STATIC_CODE                 1047
#define IDC_BUTTON_JOG_ZP               1048
#define IDC_STATIC_COMMENT              1048
#define IDC_BUTTON_TOOL                 1049
#define IDC_BUTTON_H_UP                 1049
#define IDC_BUTTON_2                    1049
#define IDC_STATIC_MESSAGE_BKG          1049
#define IDC_BUTTON_JOG_YM               1050
#define IDC_BUTTON_JOG_XP               1051
#define IDC_BUTTON_TERM                 1052
#define IDC_BUTTON_JOG_YP               1053
#define IDC_BUTTON_IO                   1054
#define IDC_BUTTON_LOG                  1055
#define IDC_BUTTON9                     1056
#define IDC_BUTTON_MULTIORG             1056
#define IDC_BUTTON_MAINTENANCE          1056
#define IDC_BUTTON10                    1057
#define IDC_BUTTON_AUTO_TEACHING        1057
#define IDC_BUTTON11                    1058
#define IDC_BUTTON_SYSTEM               1058
#define IDC_BUTTON_SERVICE              1059
#define IDC_BUTTON_DOWNLOAD_TO_CTRL     1060
#define IDC_BUTTON_UPOAD_TO_PC          1061
#define IDC_BUTTON_SAV                  1062
#define IDC_BUTTON_RESET_TOOL_3         1063
#define IDC_BUTTON_ENTER                1063
#define IDC_CHECK_JOG_MODE              1063
#define IDC_BUTTON_TEACHING             1064
#define IDC_BUTTON_STEP_VAL             1064
#define IDC_BUTTON_RESET_TOOL_4         1065
#define IDC_CHECK_JOG_MODE2             1065
#define IDC_BUTTON_GET_TOOL_5           1066
#define IDC_BUTTON_RESET_TOOL_5         1067
#define IDC_BUTTON_GET_TOOL_6           1068
#define IDC_BUTTON_RESET_TOOL_6         1069
#define IDC_BUTTON_TIME_TOOL_1          1070
#define IDC_BUTTON_TIME_TOOL_2          1071
#define IDC_BUTTON_TIME_TOOL_3          1072
#define IDC_BUTTON_GET_TOOL_1           1074
#define IDC_BUTTON_RESET_TOOL_1         1075
#define IDC_BUTTON_GET_TOOL_2           1076
#define IDC_BUTTON_GET_TOOL_3           1077
#define IDC_BUTTON_GET_TOOL_4           1078
#define IDC_BUTTON_RESET_TOOL_2         1079
#define IDC_STATIC_TOOL_1               1080
#define IDC_STATIC_TOOL_2               1081
#define IDC_STATIC_TOOL_3               1082
#define IDC_STATIC_TOOL_4               1083
#define IDC_STATIC_TOOL_5               1084
#define IDC_STATIC_TOOL_6               1085
#define IDC_STATIC_TOOL_7               1086
#define IDC_BUTTON_TOOL_1               1086
#define IDC_STATIC_TOOL_8               1087
#define IDC_BUTTON_TIME_TOOL_4          1087
#define IDC_BUTTON_TIME_TOOL_5          1088
#define IDC_BUTTON_TIME_TOOL_6          1089
#define IDC_BUTTON_RESET_TOOL_NO        1090
#define IDC_BUTTON_TOOL_RETURN          1091
#define IDC_BUTTON_AUTOLOADER           1092
#define IDC_BUTTON_TOOL2_RETURN         1092
#define IDC_BUTTON_AUTO_CALIBRATION     1092
#define IDC_BUTTON_OPTION               1093
#define IDC_BUTTON_RESET_TOOL_NO2       1093
#define IDC_BUTTON_RESET_TOOL2_NO       1093
#define IDC_BUTTON_H_DN                 1094
#define IDC_BUTTON_SET_TOOL_NO          1094
#define IDC_BUTTON_M_UP                 1095
#define IDC_BUTTON_SET_TOOL_NO2         1095
#define IDC_BUTTON_SET_TOOL2_NO         1095
#define IDC_BUTTON_TOOL_2               1095
#define IDC_BUTTON_M_DN                 1096
#define IDC_BUTTON_TOOL_3               1096
#define IDC_BUTTON_S_UP                 1097
#define IDC_BUTTON_TOOL_4               1097
#define IDC_BUTTON_S_DN                 1098
#define IDC_BUTTON_TOOL_5               1098
#define IDC_STATIC_H                    1099
#define IDC_BUTTON_TOOL_6               1099
#define IDC_STATIC_M                    1100
#define IDC_STATIC_S                    1101
#define IDC_STATIC_USAGE_LABEL          1102
#define IDC_STATIC_USAGE_PCT            1102
#define IDC_STATIC_D1                   1102
#define IDC_BUTTON_RESET2               1103
#define IDC_CHECK_TOOL_CLAMP_UNCLAMP    1103
#define IDC_BUTTON_RESET_CUR            1103
#define IDC_STATIC_H1                   1103
#define IDC_CHECK_TOOL2_CLAMP_UNCLAMP   1104
#define IDC_BUTTON_RESET3               1104
#define IDC_STATIC_D2                   1104
#define IDC_STATIC_H2                   1105
#define IDC_CHECK_TOOL2_CLAMP_UNCLAMP2  1105
#define IDC_BTN_PROCEED                 1105
#define IDC_STATIC_D3                   1106
#define IDC_BUTTON_1                    1107
#define IDC_STATIC_H_CUR                1107
#define IDC_STATIC_H3                   1107
#define IDC_BUTTON_3                    1108
#define IDC_STATIC_M_CUR                1108
#define IDC_STATIC_D4                   1108
#define IDC_BUTTON_4                    1109
#define IDC_STATIC_S_CUR                1109
#define IDC_STATIC_H4                   1109
#define IDC_BUTTON_5                    1110
#define IDC_BUTTON_RESET_MAX2           1110
#define IDC_BUTTON_RESET_MAX            1110
#define IDC_BUTTON_6                    1111
#define IDC_BUTTON_7                    1112
#define IDC_BUTTON_8                    1113
#define IDC_BUTTON_9                    1114
#define IDC_BUTTON_0                    1115
#define IDC_BUTTON_SIGN                 1116
#define IDC_BUTTON_POINT                1117
#define IDC_BUTTON_BACK                 1118
#define IDC_BUTTON_ENT                  1118
#define IDC_BUTTON_CLR                  1119
#define IDC_STATIC_NUM                  1120
#define IDC_CHECK_SPINDLE_RUN           1121
#define IDC_STATIC_NUM_OLD              1121
#define IDC_BUTTON_M140                 1123
#define IDC_CHECK_SPINDLE2_RUN          1123
#define IDC_BUTTON_M141                 1124
#define IDC_BUTTON_M142                 1125
#define IDC_BUTTON_M143                 1126
#define IDC_BUTTON_M144                 1127
#define IDC_BUTTON_M145                 1128
#define IDC_BUTTON_RESET_MAX5           1128
#define IDC_BUTTON_TOOL_MANAGER         1128
#define IDC_BUTTON_M146                 1129
#define IDC_STATIC_H5                   1129
#define IDC_BUTTON_M147                 1130
#define IDC_STATIC_M4                   1130
#define IDC_STATIC_M5                   1130
#define IDC_STATIC_MGR                  1131
#define IDC_BUTTON_JOG_XM               1136
#define IDC_BUTTON_JOG_ZM               1137
#define IDC_BUTTON_JOG_AP               1138
#define IDC_BUTTON_JOG_AM               1139
#define IDC_BUTTON_JOG_BP               1140
#define IDC_BUTTON_JOG_BM               1141
#define IDC_RADIO_01                    1142
#define IDC_RADIO_02                    1143
#define IDC_STATIC_POS_WND              1143
#define IDC_RADIO_03                    1144
#define IDC_RADIO_10                    1145
#define IDC_RADIO_20                    1146
#define IDC_STATIC_COORDINATE_OFFSET_AREA 1146
#define IDC_RADIO_001                   1147
#define IDC_RADIO_002                   1148
#define IDC_BUTTON2                     1148
#define IDC_BUTTON_SET_HOME_OFFSET      1148
#define IDC_RADIO_005                   1149
#define IDC_BUTTON_G55                  1149
#define IDC_BUTTON3                     1149
#define IDC_BUTTON_UPLOAD_TO_PC         1149
#define IDC_BUTTON_MIN                  1149
#define IDC_BUTTON_CONNECT              1149
#define IDC_BUTTON_V2_RETURN_ITEMS      1149
#define IDC_BUTTON_SET_HOME_OFFSET2     1149
#define IDC_BUTTON_FILTER_MANAGEMENT    1149
#define IDC_BUTTON_SPINDLE_CLAMP        1150
#define IDC_BUTTON4                     1150
#define IDC_BUTTON_RIGHT_MIN            1150
#define IDC_BUTTON_SET_HOME_OFFSET3     1150
#define IDC_BUTTON_BLOCK_CLMAP          1151
#define IDC_BUTTON6                     1151
#define IDC_BUTTON_EMO_RESET4           1152
#define IDC_BUTTON8                     1152
#define IDC_BUTTON_M                    1153
#define IDC_BUTTON18                    1153
#define IDC_BUTTON_ATC_TEST             1153
#define IDC_BUTTON20                    1154
#define IDC_BUTTON21                    1155
#define IDC_BUTTON_JOG_SPEED_DOWN       1155
#define IDC_BUTTON_AGING                1155
#define IDC_STATIC_TEACHING_POINT_AREA  1156
#define IDC_BUTTON22                    1156
#define IDC_BUTTON_SET_CURRENT_POSITION 1157
#define IDC_BUTTON23                    1157
#define IDC_BUTTON_RUN_TIME_INFO        1157
#define IDC_BUTTON_G53                  1158
#define IDC_BUTTON24                    1158
#define IDC_BUTTON_CHANGE_IP            1158
#define IDC_BUTTON_G54                  1159
#define IDC_BUTTON_MULTI_ORIGIN         1159
#define IDC_RADIO_COORDINATE_OFFSET     1160
#define IDC_RADIO_TEACHING_POINT        1161
#define IDC_STATIC_OPTION               1161
#define IDC_RADIO_OPTION                1162
#define IDC_STATIC_AREA2                1163
#define IDC_STATIC_COORD_OSSET          1164
#define IDC_STATIC_AREA3                1164
#define IDC_STATIC_TEACHING_POINT       1165
#define IDC_BUTTON_YES                  1168
#define IDC_STATIC_MSG                  1169
#define IDC_STATIC_GB_JOG               1170
#define IDC_STATIC_TOOL_AREA            1171
#define IDC_STATIC_REL_TOOL_AREA        1172
#define IDC_STATIC_AREA                 1173
#define IDC_CHECK_USING_BLOCK_AUTOLOADER 1200
#define IDC_CHECK_USING_COMPLETE_MELODY 1201
#define IDC_CHECK_USING_LCD             1201
#define IDC_CHECK_USING_ERROR_MELODY    1202
#define IDC_CHECK_USING_DETECT_BLOCK_SENSOR 1203
#define IDC_CHECK_USING_AIR_PRESSURE_LIMIT 1204
#define IDC_CHECK_DEMO_MODE             1205
#define IDC_CHECK_USING_OP_PANEL        1206
#define IDC_STATIC_BLOCK_GRIP_INTERVAL  1207
#define IDC_STATIC_AIR_PRESSURE_INTERVAL 1208
#define IDC_BUTTON_SAVE                 1209
#define IDC_BUTTON_BLOCK_GRIP_INTERVAL  1210
#define IDC_STATIC_BLCHK_TORQUE         1210
#define IDC_BUTTON_AIR_PRESSURE_INTERVAL 1211
#define IDC_STATIC_TEACHING_POSITION_TITLE 1212
#define IDC_STATIC_BLOCK_GRIP_INTERVAL2 1212
#define IDC_BUTTON_BLCHK_TORQUE         1212
#define IDC_STATIC_TITLE_COORD_OFFSET   1213
#define IDC_STATIC_TOOL_ERROR_MSG       1213
#define IDC_STATIC_TITLE_TEACHING_POINT 1214
#define IDC_CHECK_USING_FLOW_SENSOR     1214
#define IDC_STATIC_TEACHING_OTION_TITLE_AREA 1215
#define IDC_BUTTON_FLOW_SENSOR_TIMEOUT  1215
#define IDC_STATIC_TOOL_TITLE_AREA      1216
#define IDC_STATIC_FLOW_SENSOR_TIMEOUT  1216
#define IDC_STATIC_NCFILE_LOADING       1217
#define IDC_STATIC_IMG2_TITLE           1217
#define IDC_CHECK_INVALID_NC_CODE       1218
#define IDC_STATIC_IMG2_TITLE2          1218
#define IDC_STATIC_IMG3_TITLE           1218
#define IDC_STATIC_SUCCESS_TXT1         1218
#define IDC_CHECK_NC_FILE_TAG           1219
#define IDC_CHECK_TRANSFORM_COORDINATE  1220
#define IDC_STATIC_TITLE_AL_ROBOT2      1220
#define IDC_STATIC_T_TYPE               1221
#define IDC_CHECK_USING_SPINDLE_AIR_PURGE 1221
#define IDC_STATIC_T_CODE               1222
#define IDC_BUTTON_FLOW_SENSOR_TIMEOUT2 1222
#define IDC_BUTTON_FLOW_SENSOR_START_TIMEOUT 1222
#define IDC_STATIC_T_MESSAGE            1223
#define IDC_CHECK_USING_LOGGING         1223
#define IDC_STATIC_PURGE_AIR_HOLD_TIME  1224
#define IDC_BUTTON_PURGE_AIR_HOLD_TIME  1225
#define IDC_STATIC_TE_1                 1226
#define IDC_STATIC_FLOW_SENSOR_TIMEOUT2 1226
#define IDC_STATIC_FLOW_SENSOR_START_TIMEOUT 1226
#define IDC_STATIC_TE_2                 1227
#define IDC_BUTTON_TOOLS14              1227
#define IDC_STATIC_TE_3                 1228
#define IDC_BUTTON_M28                  1228
#define IDC_STATIC_TOOLS14              1228
#define IDC_STATIC_TE_4                 1229
#define IDC_BUTTON_EMO_RESET            1229
#define IDC_BUTTON_SERVO_ONOFF          1229
#define IDC_CHECK_BLCHK                 1229
#define IDC_STATIC_TE_5                 1230
#define IDC_CHECK_MACHINE_ID            1230
#define IDC_STATIC_TE_6                 1231
#define IDC_BUTTON_TOOLS25              1231
#define IDC_STATIC_TE_7                 1232
#define IDC_BUTTON_M29                  1232
#define IDC_BUTTON_WATER                1232
#define IDC_CHECK_WATER                 1232
#define IDC_STATIC_TOOLS25              1232
#define IDC_STATIC_TE_8                 1233
#define IDC_BUTTON_TOOLS36              1233
#define IDC_BUTTON_TOOLS3               1233
#define IDC_BUTTON_EMO_RESET2           1234
#define IDC_STATIC_TOOL_NUM_LABEL       1234
#define IDC_STATIC_TOOLS36              1234
#define IDC_STATIC_TOOLS3               1234
#define IDC_CHECK_TOOL_MAX_USAGE_TIME   1235
#define IDC_STATIC_TOOL2_NUM_LABEL2     1235
#define IDC_STATIC_TOOL2_NUM_LABEL      1235
#define IDC_CHECK_SPINDLE_OFFSET        1235
#define IDC_EDIT_PASSWORD               1236
#define IDC_STATIC_TOOL_NUM_EMPTY       1236
#define IDC_STATIC_blchk_speed          1236
#define IDC_STATIC_TOOL2_NUM_LABEL3     1237
#define IDC_STATIC_TOOL2_NUM_EMPTY      1237
#define IDC_BUTTON_TOOLS6               1237
#define IDC_RADIO_SELECT_OPER_M28       1238
#define IDC_STATIC_LABEL_MAX_D1         1238
#define IDC_BUTTON_BLCHK_SPEED          1238
#define IDC_RADIO_SELECT_OPER_M28_2     1239
#define IDC_CHECK_NO_NDDE_PASSWORD      1239
#define IDC_STATIC_LABEL_MAX_H1         1239
#define IDC_STATIC_LAST1                1239
#define IDC_BUTTON1                     1240
#define IDC_RADIO_TOOL_ERR_OCCURED_STOP 1240
#define IDC_STATIC_LABEL_D1             1240
#define IDC_STATIC_LABEL_LAST1          1240
#define IDC_STATIC_TOOLS6               1240
#define IDC_BUTTON12                    1241
#define IDC_BUTTON5                     1241
#define IDC_RADIO_TOOL_ERR_RESTART_FROM_TOOL_CHANGE_LINE 1241
#define IDC_STATIC_LABEL_H1             1241
#define IDC_STATIC_LABEL_NEXT1          1241
#define IDC_BUTTON13                    1242
#define IDC_BUTTON7                     1242
#define IDC_RADIO_TOOL_ERR_OCCURED_RESTART_FROM_BEGIN 1242
#define IDC_STATIC_LABEL_MAX_D2         1242
#define IDC_BUTTON14                    1243
#define IDC_RADIO_TOOL_ERR_OCCURED_START_NEXT_NC_FILE 1243
#define IDC_STATIC_LABEL_MAX_H2         1243
#define IDC_STATIC_NEXT1                1243
#define IDC_BUTTON15                    1244
#define IDC_RADIO_TOOL_ERR_OCCURED_USER_CONFIRM 1244
#define IDC_STATIC_LABEL_D2             1244
#define IDC_STATIC_LABEL_CURR_DATE      1244
#define IDC_STATIC_OUTPUT               1245
#define IDC_BUTTON_UNSELECT_ALL         1245
#define IDC_BUTTON25                    1245
#define IDC_STATIC_LABEL_H2             1245
#define IDC_STATIC_LABEL_LAST2          1245
#define IDC_STATIC_INPUT                1246
#define IDC_BUTTON19                    1246
#define IDC_STATIC_LABEL_MAX_D3         1246
#define IDC_STATIC_TITLE                1247
#define IDC_BUTTON_IO_4                 1247
#define IDC_STATIC_LABEL_MAX_H3         1247
#define IDC_STATIC_LABEL_NEXT2          1247
#define IDC_BUTTON26                    1248
#define IDC_BUTTON_MAXXLINK_LISTEN_PORT_NO 1248
#define IDC_STATIC_LABEL_D3             1248
#define IDC_STATIC_LAST2                1248
#define IDC_EDIT_SEND                   1249
#define IDC_BUTTON_MAXXLINK_FILERECEVIER_PORT_NO 1249
#define IDC_STATIC_LABEL_H3             1249
#define IDC_STATIC_NEXT2                1249
#define IDC_BUTTON_REMOTEPNC_LISTEN_PORT_NO 1250
#define IDC_STATIC_LABEL_IN1            1250
#define IDC_STATIC_LABEL_LAST3          1250
#define IDC_BUTTON_REMOTEPNC_FILERECEIVER_PORT_NO 1251
#define IDC_STATIC_LABEL_IN2            1251
#define IDC_STATIC_LABEL_NEXT3          1251
#define IDC_STATIC_COLLET               1252
#define IDC_BUTTON_Q                    1253
#define IDC_STATIC_LABEL_IN3            1253
#define IDC_STATIC_LAST3                1253
#define IDC_BUTTON_W                    1254
#define IDC_STATIC_LABEL_IN5            1254
#define IDC_STATIC_TOOL_STATUS          1254
#define IDC_BUTTON_E                    1255
#define IDC_STATIC_LABEL_H5             1255
#define IDC_BUTTON_R                    1256
#define IDC_STATIC_LABEL_M4             1256
#define IDC_STATIC_LABEL_M5             1256
#define IDC_BUTTON_T                    1257
#define IDC_STATIC_TOOL                 1257
#define IDC_BUTTON_Y                    1258
#define IDC_BUTTON_MUL                  1258
#define IDC_STATIC_ACTION               1258
#define IDC_BUTTON_U                    1259
#define IDC_BUTTON_DIV                  1259
#define IDC_STATIC_NEXT_MAINTENANCE     1259
#define IDC_BUTTON_I                    1260
#define IDC_BUTTON_CALC                 1260
#define IDC_STATIC_MAINTENANCE_INTERVAL 1260
#define IDC_BUTTON_O                    1261
#define IDC_STATIC_NOZZLES              1261
#define IDC_BUTTON_P                    1262
#define IDC_BUTTON_CLEAR                1262
#define IDC_STATIC_LABEL_IN6            1262
#define IDC_STATIC_LABEL_IN4            1262
#define IDC_STATIC_NEXT3                1262
#define IDC_CHECK_SEND_MODE             1263
#define IDC_STATIC_LABEL_D4             1263
#define IDC_BUTTON_A                    1264
#define IDC_STATIC_LABEL_H4             1264
#define IDC_BUTTON_S                    1265
#define IDC_STATIC_LABEL_MAX_D4         1265
#define IDC_BUTTON_D                    1266
#define IDC_STATIC_LABEL_MAX_H4         1266
#define IDC_BUTTON_F                    1267
#define IDC_BUTTON_G                    1268
#define IDC_STATIC_LABEL_LAST4          1268
#define IDC_BUTTON_H                    1269
#define IDC_STATIC_LABEL_NEXT4          1269
#define IDC_BUTTON_J                    1270
#define IDC_STATIC_LAST4                1270
#define IDC_BUTTON_K                    1271
#define IDC_STATIC_NEXT4                1271
#define IDC_BUTTON_L                    1272
#define IDC_BUTTON_TILT                 1273
#define IDC_BUTTON_Z                    1274
#define IDC_BUTTON_X                    1275
#define IDC_BUTTON_C                    1276
#define IDC_BUTTON_V                    1277
#define IDC_BUTTON_B                    1278
#define IDC_BUTTON_N                    1279
#define IDC_BUTTON_COMMA                1281
#define IDC_BUTTON_MINUS                1283
#define IDC_BUTTON_PLUS                 1284
#define IDC_BUTTON_BRACKET1             1285
#define IDC_BUTTON_BRACKET2             1286
#define IDC_BUTTON_COLON                1287
#define IDC_BUTTON_QUOTE                1288
#define IDC_BUTTON_QUEST                1289
#define IDC_LIST_HISTO                  1290
#define IDC_BUTTON_H_B                  1291
#define IDC_BUTTON_SPACE                1292
#define IDC_BUTTON_SEND                 1293
#define IDC_BUTTON_REFRESH              1293
#define IDC_BUTTON_COPY_TO_USB          1294
#define IDC_CHECK_SHIFT                 1295
#define IDC_STATIC_FILE_LIST_AREA       1295
#define IDC_BUTTON_SELECT_ALL           1296
#define IDC_BUTTON_MOVE_XY              1297
#define IDC_BUTTON_AB_JOG               1298
#define IDC_STATIC_EPNCM_VER            1299
#define IDC_STATIC_EPNCUI_VER           1300
#define IDC_STATIC_FILE_RECV_VER        1301
#define IDC_STATIC_MACHINE_MODEL        1301
#define IDC_STATIC_IP_ADDRESS           1302
#define IDC_STATIC_IO_MAP_VERSION       1303
#define IDC_STATIC_PA_CONTROLLER_VER    1304
#define IDC_STATIC_PA_CONTROLLER_DATE   1305
#define IDC_BUTTON_JOG_SPEED_UP         1308
#define IDC_STATIC_JOG_SPEED            1310
#define IDC_STATIC_SPINDLE_RPM          1314
#define IDC_CHECK_SET_SAME_DATA         1315
#define IDC_STATIC_TOOL1_NUM            1315
#define IDC_STATIC_TOOL_NO              1315
#define IDC_STATIC_SPINDLE_RPM3         1315
#define IDC_STATIC_SPINDLE2_RPM         1315
#define IDC_BUTTON_SPINDLE2_RPM         1315
#define IDC_BUTTON_CALCULATOR           1316
#define IDC_STATIC_MILLING_TIME         1316
#define IDC_BUTTON_MOVE_DATA            1317
#define IDC_STATIC_PROG_RATE            1317
#define IDC_STATIC_DATA                 1318
#define IDC_STATIC_TOOL_TIME            1318
#define IDC_BUTTON_BRACKET_OPEN         1319
#define IDC_STATIC_SPINDLE_RPM2         1319
#define IDC_STATIC_TOOL_EMPTY           1319
#define IDC_STATIC_AT_SCOPE             1319
#define IDC_BUTTON_BRACKET_CLOSE        1320
#define IDC_STATIC_TOOL_NO_2            1320
#define IDC_BUTTON_RETRY                1321
#define IDC_STATIC_TOOL_TIME2           1321
#define IDC_BUTTON_SOFT_LIMIT           1322
#define IDC_STATIC_TOOL1_HEALTH         1322
#define IDC_BUTTON_SPINDLE_INFO         1323
#define IDC_STATIC_TOOL4_HEALTH         1323
#define IDC_STATIC_LIST_AREA            1324
#define IDC_STATIC_TOOL1_HEALTH2        1324
#define IDC_STATIC_TOOL2_HEALTH         1324
#define IDC_STATIC_TITLE_AREA           1325
#define IDC_STATIC_TOOL5_HEALTH         1325
#define IDC_BUTTON_UPLOAD               1326
#define IDC_STATIC_TOOL3_HEALTH         1326
#define IDC_BUTTON_DOWNLOAD_SAVE        1327
#define IDC_STATIC_TOOL6_HEALTH         1327
#define IDC_BUTTON_AUTO_CALC_TOOLPOS    1328
#define IDC_STATIC_TOOL_NO_3            1328
#define IDC_STATIC_TOOL2_EMPTY          1328
#define IDC_BUTTON_JOG_MODE_STEP        1329
#define IDC_BUTTON_JOG_MODE_CONTINUE    1330
#define IDC_STATIC_START_TIME           1330
#define IDC_BUTTON_DOWNLOAD_TO_COLTROLLOR 1331
#define IDC_BUTTON_AUTO_CALC_TOOLPOS2   1331
#define IDC_STATIC_FINISH_TIME          1331
#define IDC_STATIC_LBL_TOTAL_TIME2      1333
#define IDC_STATIC_LBL_LEFT_TOTAL_TIME  1333
#define IDC_STATIC_CURRENT_TIME         1334
#define IDC_STATIC_LBL_LEFT_SPINDLE     1334
#define IDC_STATIC_TIME                 1335
#define IDC_STATIC_LBL_RIGHT_TOTAL_TIME 1335
#define IDC_STATIC_LBL_RIGHT_SPINDLE    1336
#define IDC_BUTTON_SET                  1337
#define IDC_BUTTON_RESET                1338
#define IDC_BUTTON_RIGHT_SET            1339
#define IDC_BUTTON_RIGHT_RESET          1340
#define IDC_BUTTON_HOUR                 1342
#define IDC_BUTTON_SEC                  1343
#define IDC_BUTTON_UPGRADE              1344
#define IDC_BUTTON_RIGHT_HOUR           1344
#define IDC_BUTTON_RIGHT_SEC            1345
#define IDC_STATIC_MSG1                 1346
#define IDC_STATIC_MSG2                 1347
#define IDC_BUTTON_SERVO_ON             1348
#define IDC_EDIT_LINE_NO                1349
#define IDC_BUTTON_FROM_SELECTED_LINE   1350
#define IDC_BUTTON_FROM_BEGINING        1351
#define IDC_BUTTON_LINE_NO              1352
#define IDC_BUTTON_V2_SETUP             1354
#define IDC_BUTTON_V2_EMO               1355
#define IDC_STATIC_TOOL_TITLE           1356
#define IDC_STATIC_TOOL_STATUS_1        1357
#define IDC_STATIC_INFO                 1357
#define IDC_STATIC_TOOL_STATUS_2_1      1358
#define IDC_STATIC_ERROR                1358
#define IDC_CHECK_DUMMY                 1358
#define IDC_STATIC_TOOL_STATUS_2_2      1359
#define IDC_STATIC_QUEST                1359
#define IDC_CHECK_AAXIS_HORIZ           1359
#define IDC_CHECK_X_AXIS_CENTER         1359
#define IDC_STATIC_TOOL_STATUS_2_3      1360
#define IDC_STATIC_WARM                 1360
#define IDC_CHECK_XAXIS_CENTER          1360
#define IDC_CHECK_Y2AXIS_CENTER         1360
#define IDC_STATIC_TOOL_STATUS_3        1361
#define IDC_CHECK_BAXIS_HORIZ           1361
#define IDC_CHECK_Y1AXIS_CENTER         1361
#define IDC_STATIC_SPINDLE_TITLE        1362
#define IDC_CHECK_YAXIS_CENTER          1362
#define IDC_CHECK_Z1AXIS_ORG_OFFSET     1362
#define IDC_STATIC_SPINDLE_STATUS       1363
#define IDC_CHECK_ZAXIS_ORG_OFFSET      1363
#define IDC_CHECK_Z2AXIS_ORG_OFFSET     1363
#define IDC_STATIC_FEEDRATE_TITLE       1364
#define IDC_CHECK_TOUCH_SIGNAL          1364
#define IDC_STATIC_FEEDRATE_STATUS      1365
#define IDC_BUTTON_START_STOP           1365
#define IDC_STATIC_MILLING_TIME_TITLE   1366
#define IDC_STATIC_G                    1366
#define IDC_CHECK_RIGHT_TOUCH_SIGNAL    1366
#define IDC_STATIC_MILLING_TIME_STATUS_1 1367
#define IDC_CHECK_AB_DISTANCE           1367
#define IDC_STATIC_G2                   1367
#define IDC_STATIC_MILLING_TIME_STATUS_1_1 1368
#define IDC_COMBO_SEL_USER              1368
#define IDC_CHECK_TOUCH_SIGNAL3         1368
#define IDC_STATIC_G3                   1368
#define IDC_STATIC_MILLING_TIME_STATUS_1_2 1369
#define IDC_STATIC_G4                   1369
#define IDC_STATIC_MILLING_TIME_STATUS_1_3 1370
#define IDC_STATIC_MILLING_TIME_STATUS_2 1371
#define IDC_STATIC_MILLING_TIME_STATUS_2_1 1372
#define IDC_STATIC_MILLING_TIME_STATUS_2_2 1373
#define IDC_STATIC_MILLING_TIME_STATUS_2_3 1374
#define IDC_STATIC_ICON_USB             1375
#define IDC_STATIC_ICON_REMOTR          1376
#define IDC_STATIC_ICON_BLOCK           1377
#define IDC_CHECK_TOUCH_SIGNAL2         1377
#define IDC_BUTTON_V2_START             1378
#define IDC_BUTTON_V2_PAUSE             1379
#define IDC_BUTTON_LOAD_FROM_FILE       1379
#define IDC_BUTTON_V2_STOP              1380
#define IDC_CHECK_USE_LINKER            1380
#define IDC_BUTTON_V2_OPEN              1381
#define IDC_BUTTON_LINKER_IP1           1381
#define IDC_BUTTON_V2_TOOL              1382
#define IDC_BUTTON_LINKER_IP2           1382
#define IDC_BUTTON_V2_READY_POS         1383
#define IDC_BUTTON_LINKER_IP3           1383
#define IDC_BUTTON_V2_BLOCK             1384
#define IDC_BUTTON_LINKER_IP4           1384
#define IDC_BUTTON_V2_TOOL_COLLET       1385
#define IDC_BUTTON_LINKER_PORTNO        1385
#define IDC_BUTTON_V2_TOOL_ATCDOOR      1386
#define IDC_BUTTON_SERVICE_IP1          1386
#define IDC_BUTTON_SET_HOME_OFFSET_AB   1386
#define IDC_BUTTON_V2_TOOL_RETURN       1387
#define IDC_BUTTON_SERVICE_IP2          1387
#define IDC_STATIC_RUN_TIME_LIST_AREA   1387
#define IDC_BUTTON_V2_TOOL_SETUP        1388
#define IDC_BUTTON_SERVICE_IP3          1388
#define IDC_BUTTON_AL_BLOCK_STATE_AREA  1389
#define IDC_BUTTON_SERVICE_IP4          1389
#define IDC_BUTTON_V2_NCFILE_ADD        1390
#define IDC_BUTTON_SERVICE_PORTNO       1390
#define IDC_STATIC_MC_IP                1390
#define IDC_BUTTON_V2_NCFILE_DELETE     1391
#define IDC_STATIC_IO_IP                1391
#define IDC_BUTTON_NCFILE_LIST_AREA     1392
#define IDC_BUTTON_MC_1                 1392
#define IDC_BUTTON_V2_NCFILE_UP         1393
#define IDC_BUTTON_MC_2                 1393
#define IDC_BUTTON_V2_NCFILE_DOWN       1394
#define IDC_BUTTON_MC_3                 1394
#define IDC_STATIC_NUM_SELECTED_FILE    1395
#define IDC_STATIC_NUM_SELECTED_FILE_EXPAND 1395
#define IDC_BUTTON_MC_4                 1395
#define IDC_BUTTON_V2_EXPAND            1396
#define IDC_BUTTON_IO_1                 1396
#define IDC_BUTTON_IO_2                 1397
#define IDC_STATIC_NUM_SELECTED_FILE_COLLAPSE 1398
#define IDC_BUTTON_IO_3                 1398
#define IDC_BUTTON_V2_COLLAPSE          1399
#define IDC_BUTTON_DOWNLOAD             1399
#define IDC_BUTTON_V2_FLV_COPY_TO_USB   1400
#define IDC_BUTTON_CHANGE_IP_PA         1400
#define IDC_BUTTON_V2_FLV_SELECT_ALL    1401
#define IDC_BUTTON_CHANGE_IP_IO         1401
#define IDC_BUTTON_V2_FLV_DESELECT_ALL  1402
#define IDC_CHECK_TOOL1                 1402
#define IDC_BUTTON_CHANGE_PORT_NO       1402
#define IDC_CHECK_TOOL2                 1403
#define IDC_BUTTON_CHANGE_IP_IO2        1403
#define IDC_BUTTON_CHANGE_PC_IP         1403
#define IDC_BUTTON_V2_EMO2              1403
#define IDC_CHECK_TOOL3                 1404
#define IDC_CHECK_TOOL4                 1405
#define IDC_CHECK_TOOL5                 1406
#define IDC_CHECK_TOOL6                 1407
#define IDC_CHECK_TOOL7                 1408
#define IDC_CHECK_TOOL8                 1409
#define IDC_EDIT_TOOL1                  1410
#define IDC_EDIT_TOOL1_ME               1411
#define IDC_EDIT_TOOL2                  1412
#define IDC_EDIT_TOOL2_ME               1413
#define IDC_EDIT_TOOL3                  1414
#define IDC_EDIT_TOOL3_ME               1415
#define IDC_EDIT_TOOL4                  1416
#define IDC_EDIT_TOOL4_ME               1417
#define IDC_EDIT_TOOL5                  1418
#define IDC_EDIT_TOOL5_ME               1419
#define IDC_EDIT_TOOL6                  1420
#define IDC_EDIT_TOOL6_ME               1421
#define IDC_EDIT_TOOL7                  1422
#define IDC_EDIT_TOOL7_ME               1423
#define IDC_EDIT_TOOL8                  1424
#define IDC_EDIT_TOOL8_ME               1425
#define IDC_COMBO_TOOL1                 1426
#define IDC_BUTTON_MEASURE_COUNT        1427
#define IDC_COMBO_TOOL2                 1428
#define IDC_COMBO_TOOL3                 1429
#define IDC_COMBO_TOOL4                 1430
#define IDC_COMBO_TOOL5                 1431
#define IDC_COMBO_TOOL6                 1432
#define IDC_COMBO_TOOL7                 1433
#define IDC_COMBO_TOOL8                 1434
#define IDC_BUTTON_MEASURE_START        1435
#define IDC_STATIC_WORKING_COUNT        1437
#define IDC_BUTTON_V2_RESCAN_CASSETTE   1439
#define IDC_COMBO_SEL_AXIS              1440
#define IDC_BUTTON_ORIGIN               1441
#define IDC_BUTTON_MINIMIZE             1442
#define IDC_STATIC_MAIN                 1445
#define IDC_STATIC_MODEL_INFO           1445
#define IDC_STATIC_NC_FILE              1447
#define IDC_BUTTON_PA_CONNECTED         1448
#define IDC_ICN_TOOLS                   1448
#define IDC_STATIC_SYSTEM_STATUS        1449
#define IDC_BUTTON_IO_CONNECTED         1450
#define IDC_ICN_COLLETS                 1450
#define IDC_BUTTON_SPINDLE_RPM          1451
#define IDC_STATIC_PA_CONNECTED         1452
#define IDC_STATIC_TOOLS                1452
#define IDC_STATIC_IO_CONNECTED         1453
#define IDC_STATIC_COLLETS              1453
#define IDC_BUTTON_SPINDLE2_CLAMP       1454
#define IDC_BUTTON_SPINDLE_RPM2         1454
#define IDC_BUTTON_TOOL_TIME            1455
#define IDC_STATIC_TOTAL_TIME           1455
#define IDC_BUTTON_TOOL_TIME2           1456
#define IDC_BUTTON_LEFT_HOUR            1456
#define IDC_BUTTON_LOADED               1457
#define IDC_BUTTON_LEFT_MIN             1457
#define IDC_BUTTON_PA_CONNECTED3        1458
#define IDC_BUTTON_FINISHED             1458
#define IDC_BUTTON_LEFT_SEC             1458
#define IDC_BUTTON_RUNNING              1459
#define IDC_BUTTON_LEFT_SET             1459
#define IDC_BUTTON_LEFT_RESET           1460
#define IDC_STATIC_TOOL_ERROR           1460
#define IDC_BUTTON_LOADED2              1460
#define IDC_BUTTON_DART                 1460
#define IDC_CHECK_LEFT_TOUCH_SIGNAL     1461
#define IDC_STATIC_TOOL_ALARM           1461
#define IDC_CHECK_LEFT_TOOL_POCKET      1462
#define IDC_BUTTON_TOOL_ERROR_STATE     1462
#define IDC_CHECK_RIGHT_TOOL_POCKET     1463
#define IDC_BUTTON_TOOL_ERROR_STATE2    1463
#define IDC_BUTTON_TOOL_ALARM_STATE     1463
#define IDC_COMBOBOXEX1                 1464
#define IDC_RADIO_TOOL_14               1466
#define IDC_BUTTON_PA_CONNECTED2        1466
#define IDC_ICN_COOLANT                 1466
#define IDC_RADIO_TOOL_25               1467
#define IDC_ICN_FILTER                  1467
#define IDC_RADIO_TOOL_36               1468
#define IDC_STATIC_COOLANT              1468
#define IDC_RADIO_TOOL_0                1469
#define IDC_STATIC_FILTER               1469
#define IDC_STATIC_TOOL_SELECTION       1470
#define IDC_STATIC_DOOR                 1470
#define IDC_BUTTON_APPLY                1471
#define IDC_ICN_DOOR                    1471
#define IDC_STATIC_TOOLNO               1472
#define IDC_STATIC_TOOL2_NUM            1472
#define IDC_STATIC_CONNECTION           1472
#define IDC_STATIC_TOOL_NUM             1473
#define IDC_STATIC_TOOL_TIME_CUR_HEADING 1473
#define IDC_STATIC_TOOL_TIME_LABEL      1473
#define IDC_STATIC_MAINTENANCE          1473
#define IDC_STATIC_TOOL_TIME_HEADING2   1474
#define IDC_STATIC_TOOL_TIME_HEADING    1474
#define IDC_STATIC_READY                1474
#define IDC_CHECK1                      1475
#define IDC_CHECK_MAXTIME_LABEL         1475
#define IDC_ICN_DOOR2                   1475
#define IDC_ICN_CONNECTION              1475
#define IDC_STATIC_TOOL_TIME_CUR_HEADING2 1476
#define IDC_ICN_MAINTENANCE             1476
#define IDC_STATIC_TOOL_NUM2            1477
#define IDC_STATIC_TOOL_TIME_NUM        1477
#define IDC_ICN_READY                   1477
#define IDC_STATIC_TOOL_TIME_CUR_HEADING3 1478
#define IDC_STATIC_TOOL_TIME_CUR_LABEL  1478
#define IDC_ICN_FILTER2                 1478
#define IDC_ICN_NOZZLE                  1478
#define IDC_STATIC_TOOL_TIME_CUR_HEADING4 1479
#define IDC_STATIC_TOOL_TIME_USAGE_LABEL 1479
#define IDC_STATIC_MILLING_STATUS       1479
#define IDC_STATIC_START_TIME_LABEL     1480
#define IDC_STATIC_TOOL_TIME_USAGE_LABEL2 1480
#define IDC_STATIC_MILLINGS_LEFT        1480
#define IDC_STATIC_NOZZLE               1481
#define IDC_STATIC_FINISH_TIME_LABEL    1482
#define IDC_BUTTON_RESET1               1482
#define IDC_BUTTON_MAINTENANCE1         1482
#define IDC_STATIC_MAX_D1               1483
#define IDC_STATIC_VERSION              1483
#define IDC_STATIC_MAX_H1               1484
#define IDC_STATIC_MAX_D5               1484
#define IDC_STATIC_CURR_DATE            1484
#define IDC_STATIC_MACHINEID            1484
#define IDC_STATIC_MACHINE_ID           1484
#define IDC_BUTTON_UP_H1                1485
#define IDC_STATIC_STATUS_LINE3         1485
#define IDC_BUTTON_DOWN_H1              1486
#define IDC_BUTTON_DOWN_D1              1487
#define IDC_BUTTON_UP_D1                1488
#define IDC_BUTTON_UP_D2                1489
#define IDC_BUTTON_UP_D3                1490
#define IDC_STATIC_MAX_D2               1491
#define IDC_BUTTON_DOWN_D2              1492
#define IDC_BUTTON_UP_H2                1493
#define IDC_STATIC_GB_1                 1493
#define IDC_STATIC_MAX_H2               1494
#define IDC_STATIC_HEADING              1494
#define IDC_BUTTON_DOWN_H2              1495
#define IDC_STATIC_GB_2                 1495
#define IDC_BUTTON_MAINTENANCE2         1496
#define IDC_BUTTON_TEST_LCD             1496
#define IDC_STATIC_MAX_D3               1497
#define IDC_RADIO_SELECT_FULL           1497
#define IDC_BUTTON_DOWN_D3              1498
#define IDC_RADIO_SELECT_ONLY           1498
#define IDC_BUTTON_UP_H3                1499
#define IDC_STATIC_GB_3                 1499
#define IDC_STATIC_AT_TYPE              1499
#define IDC_STATIC_MAX_H3               1500
#define IDC_STATIC_GB_4                 1500
#define IDC_BUTTON_DOWN_H3              1501
#define IDC_STATIC_GB_5                 1501
#define IDC_BUTTON_STEP_PREVIOUS        1501
#define IDC_BUTTON_MAINTENANCE3         1502
#define IDC_BUTTON_STEP_NEXT            1502
#define IDC_BUTTON_SAVE1                1503
#define IDC_RADIO_STEP1                 1503
#define IDC_BUTTON_SAVE2                1504
#define IDC_RADIO_STEP2                 1504
#define IDC_BUTTON_SAVE3                1505
#define IDC_RADIO_STEP3                 1505
#define IDC_BUTTON_MAINTENANCE4         1506
#define IDC_RADIO_STEP4                 1506
#define IDC_BUTTON_UP_D4                1507
#define IDC_RADIO_STEP5                 1507
#define IDC_STATIC_MAX_D4               1508
#define IDC_RADIO_STEP6                 1508
#define IDC_BUTTON_DOWN_D4              1509
#define IDC_STATIC_CURRENT_STEP         1509
#define IDC_BUTTON_UP_H4                1510
#define IDC_RADIO_STEP7                 1510
#define IDC_STATIC_IMG1                 1510
#define IDC_STATIC_MAX_H4               1511
#define IDC_STATIC_IMG2                 1511
#define IDC_BUTTON_DOWN_H4              1512
#define IDC_STATIC_IMG1_TITLE           1512
#define IDC_BUTTON_SAVE4                1513
#define IDC_STATIC_IMG3                 1513
#define IDC_STATIC_ARROW_12             1513
#define IDC_STATIC_IMG1_DESC            1513
#define IDC_STATIC_IMG1_TITLE2          1513
#define IDC_STATIC_SUBSTEP2             1513
#define IDC_STATIC_IMG4                 1514
#define IDC_STATIC_ARROW_23             1514
#define IDC_STATIC_IMG1_DEST            1514
#define IDC_STATIC_IMG1_DESCR           1514
#define IDC_STATIC_IMG1_TITLE3          1514
#define IDC_STATIC_SUBSTEP3             1514
#define IDC_STATIC_ARROW_34             1515
#define IDC_STATIC_SUBSTEP2_DESC        1515
#define IDC_STATIC_ARROW_45             1516
#define IDC_STATIC_ARROW_56             1517
#define IDC_STATIC_ARROW_67             1518
#define IDC_STATIC_SUBSTEP1             1519
#define IDC_STATIC_SUCCESS_TXT2         1520

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1521
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
